spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lunchproject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 123!@#qweQWE
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
