spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/lunchproject
    username: root
    password: koreait
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp