spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/lunchproject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: koreait
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB